namespace Elmah.SignalR.Test
{
    #region Imports

    using System;

    #endregion

    // Simple error representation, so far
    // its only purpose is to simplify deserialization
    // of the json representation. It should resemble, 
    // when complete, an error representation
    // generated by Elmah.

    public class Error
    {
        public string   host, type, message;
        public DateTime time;
    }

    public class Application
    {
        public int id;
        public string name;
        public Error error;
    }

}