namespace Elmah.SignalR.Test
{
    #region Imports

    using System;
    using System.Collections.Generic;

    #endregion

    // Simple error representation, so far
    // its only purpose is to simplify deserialization
    // of the json representation. It should resemble, 
    // when complete, an error representation
    // generated by Elmah.

    public class Error
    {
        public string                       host, 
                                            type, 
                                            message, 
                                            source, 
                                            detail, 
                                            user, 
                                            statusCode, 
                                            webHostHtmlMessage;
        public Dictionary<string, string>   serverVariables = new Dictionary<string, string>(),
                                            form = new Dictionary<string, string>(),
                                            cookies = new Dictionary<string, string>();
        public DateTime                     time;

        public string                       url,
                                            shortType,
                                            browserSupportUrl;

        public bool                         hasYsod;
    }
}